<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RichfieldHackathonBackend.Application\RichfieldHackathonBackend.Application.csproj" />
    <ProjectReference Include="..\RichfieldHackathonBackend.Domain\RichfieldHackathonBackend.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
